version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "workflow-engine"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-1dl7e6dfrw4b3"
s3_prefix = "workflow-engine"
region = "eu-central-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
image_repositories = []
parameter_overrides = "S3BucketName=\"workflow-engine-store\""
