AWSTemplateFormatVersion : '2010-09-09'
Transform: AWS::Serverless-2016-10-31

Parameters:
  S3BucketName:
    Type: String
    Default: async-sequence-store
    Description: Enter S3 Bucket Name. Default is async-sequence-store

Globals:
  Function:
    Runtime: python3.8
    Timeout: 180
    Layers:
      - !Ref AsyncSequenceDepends
    Environment:
      Variables:
        BUCKET_NAME: !Ref S3BucketName
        
Resources:
  CompositionStore:
      Type: AWS::S3::Bucket
      Properties:
        BucketName: !Ref S3BucketName

  AsyncSequenceFunctionA:
    Type: AWS::Serverless::Function
    Properties:
      Handler: function_a.lambda_handler
      FunctionName: AsyncSequenceFunctionA
      Policies:
        - LambdaInvokePolicy:
            FunctionName: AsyncSequenceFunctionB

  AsyncSequenceFunctionB:
    Type: AWS::Serverless::Function
    Properties:
      Handler: function_b.lambda_handler
      FunctionName: AsyncSequenceFunctionB
      Policies:
        - LambdaInvokePolicy:
            FunctionName: AsyncSequenceFunctionC

  AsyncSequenceFunctionC:
    Type: AWS::Serverless::Function
    Properties:
      Handler: function_c.lambda_handler
      FunctionName: AsyncSequenceFunctionC
      Policies:
        - S3WritePolicy:
            BucketName: !Ref S3BucketName

  AsyncSequenceDepends:
    Type: AWS::Serverless::LayerVersion
    Properties:
      LayerName: AsyncSequenceDepends
      CompatibleRuntimes:
          - python3.8
      ContentUri: ../aws_helpers
      Description: Utility Functions for Async Sequence Composition
      LicenseInfo: MIT
    Metadata:
      BuildMethod: python3.8
