AWSTemplateFormatVersion : '2010-09-09'
Transform: AWS::Serverless-2016-10-31

Parameters:
  S3BucketName:
    Type: String
    Default: storage-based-store
    Description: Enter S3 Bucket Name. Default is storage-based-store

Globals:
  Function:
    Runtime: python3.9
    Timeout: 180
    Environment:
      Variables:
        BUCKET_NAME: !Ref S3BucketName
    Layers:
        - !Ref StorageBasedDepends

Resources:
  CompositionStore:
      Type: AWS::S3::Bucket
      Properties:
        BucketName: !Ref S3BucketName 

  StorageBasedFunctionA:
    Type: AWS::Serverless::Function
    Properties:
      Handler: function_a.lambda_handler
      FunctionName: StorageBasedFunctionA

      Policies:
        - S3WritePolicy:
            BucketName: !Ref S3BucketName
        - S3ReadPolicy:
            BucketName: !Ref S3BucketName
      Events:
        S3Event:
          Type: S3
          Properties:
            Bucket: !Ref CompositionStore
            Events: s3:ObjectCreated:Put
            Filter:
              S3Key:
                Rules:
                - Name: prefix
                  Value: function_a

  StorageBasedFunctionB:
    Type: AWS::Serverless::Function
    Properties:
      Handler: function_b.lambda_handler
      FunctionName: StorageBasedFunctionB

      Policies:
        - S3WritePolicy:
            BucketName: !Ref S3BucketName
        - S3ReadPolicy:
            BucketName: !Ref S3BucketName
      Events:
        S3Event:
          Type: S3
          Properties:
            Bucket: !Ref CompositionStore
            Events: s3:ObjectCreated:Put
            Filter:
              S3Key:
                Rules:
                - Name: prefix
                  Value: function_b

  StorageBasedFunctionC:
    Type: AWS::Serverless::Function
    Properties:
      Handler: function_c.lambda_handler
      FunctionName: StorageBasedFunctionC
      
      Policies:
        - S3WritePolicy:
            BucketName: !Ref S3BucketName
        - S3ReadPolicy:
            BucketName: !Ref S3BucketName
      Events:
        S3Event:
          Type: S3
          Properties:
            Bucket: !Ref CompositionStore
            Events: s3:ObjectCreated:Put
            Filter:
              S3Key:
                Rules:
                - Name: prefix
                  Value: function_c

  StorageBasedDepends:
    Type: AWS::Serverless::LayerVersion
    Properties:
      CompatibleRuntimes:
          - python3.9
      ContentUri: ../aws_helpers
      Description: Utility Functions for Message Queue Composition
      LicenseInfo: MIT
    Metadata:
      BuildMethod: python3.9
