version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "async-function-sequence"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-1dl7e6dfrw4b3"
s3_prefix = "async-function-sequence"
region = "eu-central-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
parameter_overrides = "S3BucketName=\"async-sequence-store\""
image_repositories = []
