AWSTemplateFormatVersion : '2010-09-09'
Transform: AWS::Serverless-2016-10-31

Globals:
  Function:
    Runtime: python3.9
    Timeout: 180

Resources:  
  AsyncSequenceFunctionA:
    Type: AWS::Serverless::Function
    Properties:
      Handler: app.a
      FunctionName: AsyncSequenceFunctionA
      Events:
        FunctionA:
          Type: Api
          Properties:
            Path: /a
            Method: get
      Policies:
        - LambdaInvokePolicy:
            FunctionName: AsyncSequenceFunctionB
  AsyncSequenceFunctionB:
    Type: AWS::Serverless::Function
    Properties:
      Handler: app.b
      FunctionName: AsyncSequenceFunctionB
      Policies:
        - LambdaInvokePolicy:
            FunctionName: AsyncSequenceFunctionC
  AsyncSequenceFunctionC:
    Type: AWS::Serverless::Function
    Properties:
      Handler: app.c
      FunctionName: AsyncSequenceFunctionC
