AWSTemplateFormatVersion : '2010-09-09'
Transform: AWS::Serverless-2016-10-31

Parameters:
  S3BucketName:
    Type: String
    Default: message-queue-store
    Description: Enter S3 Bucket Name. Default is message-queue-store

Globals:
  Function:
    Runtime: python3.9
    Timeout: 180
    Environment:
        Variables:
          TOPIC_ARN: !Ref MessageQueueTopic
    Layers:
        - !Ref MessageQueueDepends

Resources:
  CompositionStore:
      Type: AWS::S3::Bucket
      Properties:
        BucketName: !Ref S3BucketName 

  MessageQueueTopic:
    Type: AWS::SNS::Topic
    Properties:
      TopicName: MessageQueueTopic
  # https://forum.serverless.com/t/aws-topicpolicy-invalid-template-resource-property-topics/2726/2
  # AWS:SourceOwner (default) --> AWS:PrincipalAccount is the fix for AuthorizationErrorException (boto3)
  MessageQueueTopicPolicy:
    Type: AWS::SNS::TopicPolicy
    Properties:
      PolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal:
              AWS: '*'
            Action:
              - "SNS:Publish"
            Resource: '*'
            Condition: 
              StringEquals:
                AWS:PrincipalAccount: !Ref AWS::AccountId
      Topics:
        - !Ref MessageQueueTopic

  MessageQueueFunctionA:
    Type: AWS::Serverless::Function
    Properties:
      Handler: function_a.lambda_handler
      FunctionName: MessageQueueFunctionA
      Policies:
        - SNSPublishMessagePolicy:
            TopicName: !Ref MessageQueueTopic
      Events:
        SNSEvent:
          Type: SNS
          Properties:
            Topic: !Ref MessageQueueTopic
            FilterPolicy:
              caller:
                - Client

  MessageQueueFunctionB:
    Type: AWS::Serverless::Function
    Properties:
      Handler: function_b.lambda_handler
      FunctionName: MessageQueueFunctionB
      Policies:
        - SNSPublishMessagePolicy:
            TopicName: !Ref MessageQueueTopic
      Events:
        SNSEvent:
          Type: SNS
          Properties:
            Topic: !Ref MessageQueueTopic
            FilterPolicy:
              caller:
                - MessageQueueFunctionA

  MessageQueueFunctionC:
    Type: AWS::Serverless::Function
    Properties:
      Handler: function_c.lambda_handler
      FunctionName: MessageQueueFunctionC
      Environment:
        Variables:
          BUCKET_NAME: !Ref S3BucketName
      Policies:
        - S3WritePolicy:
            BucketName: !Ref S3BucketName
      Events:
        SNSEvent:
          Type: SNS
          Properties:
            Topic: !Ref MessageQueueTopic
            FilterPolicy:
              caller:
                - MessageQueueFunctionB

  MessageQueueDepends:
    Type: AWS::Serverless::LayerVersion
    Properties:
      CompatibleRuntimes:
          - python3.9
      ContentUri: ../aws_helpers
      Description: Utility Functions for Message Queue Composition
      LicenseInfo: MIT
    Metadata:
      BuildMethod: python3.9
