AWSTemplateFormatVersion : '2010-09-09'
Transform: AWS::Serverless-2016-10-31

Parameters:
  S3BucketName:
    Type: String
    Default: routing-slip-store
    Description: Enter S3 Bucket Name. Default is routing-slip-store

Globals:
  Function:
    Runtime: python3.8
    Timeout: 180
    Environment:
      Variables:
        BUCKET_NAME: !Ref S3BucketName
    Layers:
        - !Ref RoutingSlipDepends

Resources:
  CompositionStore:
      Type: AWS::S3::Bucket
      Properties:
        BucketName: !Ref S3BucketName 

  RoutingSlipFunctionA:
    Type: AWS::Serverless::Function
    Properties:
      Handler: function_a.lambda_handler
      FunctionName: RoutingSlipFunctionA
      Policies:
        - LambdaInvokePolicy:
            FunctionName: RoutingSlipFunctionB
        - S3WritePolicy:
            BucketName: !Ref S3BucketName

  RoutingSlipFunctionB:
    Type: AWS::Serverless::Function
    Properties:
      Handler: function_b.lambda_handler
      FunctionName: RoutingSlipFunctionB
      Policies:
        - LambdaInvokePolicy:
            FunctionName: RoutingSlipFunctionC
        - S3WritePolicy:
            BucketName: !Ref S3BucketName

  RoutingSlipFunctionC:
    Type: AWS::Serverless::Function
    Properties:
      Handler: function_c.lambda_handler
      FunctionName: RoutingSlipFunctionC
      Policies:
        - S3WritePolicy:
              BucketName: !Ref S3BucketName

  RoutingSlipDepends:
    Type: AWS::Serverless::LayerVersion
    Properties:
      LayerName: RoutingSlipDepends
      CompatibleRuntimes:
          - python3.8
      ContentUri: ../aws_helpers
      Description: Utility Functions for Routing Slip
      LicenseInfo: MIT
    Metadata:
      BuildMethod: python3.8
